name: Production Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Получение env
        run: echo "${{ secrets.ENV }}" > .env.local
      - name: Билд и запуск
        run: docker compose --ansi=never -f docker-compose.yml up --build -d
